name: Check nuget

on:
  workflow_dispatch:
  schedule:
  - cron: '30 3 * * *'


jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r bin/requirements.txt

    - name: Run Check
      run: python bin/check.py

    - name: Set issue title with current date and time
      id: set_title
      run: |
        # Get current date and time in the format YYYY-MM-DD HH:MM:SS
        title=$(date +"%Y-%m-%d %H:%M:%S")
        echo "Issue title: $title"
        echo "issue_title=$title" >> $GITHUB_ENV

    - name: Create Issue
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: ${{ env.issue_title }}
        content-filepath: ./nuget.txt
        token: ${{ secrets.GITHUB_TOKEN }}
